_wandb:
    value:
        cli_version: 0.21.2
        e:
            5oedx47245kbxbu76awdzeciitwcosnd:
                args:
                    - --local_rank=0
                    - --ds_config_path
                    - ./cs336_basics/configs/ds_config.json
                    - --model_config_path
                    - ./cs336_basics/configs/model_config.json
                    - --dataset_dir
                    - ./out/ts_train
                    - --checkpoint_dir
                    - ./out/ts_train/checkpoints
                    - --save_interval
                    - "2000"
                    - --lr
                    - "6e-4"
                    - --context_length
                    - "256"
                    - --total_iters
                    - "10000"
                codePath: cs336_basics/solutions/_train_model.py
                codePathLocal: cs336_basics/solutions/_train_model.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1802368331776"
                        used: "1054804107264"
                email: sjoonyeong@gmail.com
                executable: /home/aikusrv02/_PROJECTS/wonjunoh/assignment1-basics-solution/.venv/bin/python
                git:
                    commit: 383d3e24a4b2f706dce0157e9f62f0020473070d
                    remote: https://bigohofone:@github.com/bigohofone/assignment1-basics-solution.git
                gpu: NVIDIA TITAN Xp
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-b46646ba-4720-7f6f-9b62-dc588433880a
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-0b17e316-c62a-96db-dbc0-bacc7ad7b504
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-3f6da9b7-110b-b5de-38ea-3b5acbdbc4c0
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-4c20eb6d-329d-218e-1e9a-a7c82e44dc07
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-f27c10bb-8b73-e4a6-3f6d-4b988fe9895f
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-a04c7ad4-d5fc-1efa-6351-4f700d2d4eab
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-c0357ebc-0906-3334-85c0-132191398068
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-69daa162-6eb3-83a6-d33b-b550cb5046f3
                host: aikusrv02
                memory:
                    total: "135032475648"
                os: Linux-5.15.0-168-generic-x86_64-with-glibc2.35
                program: /home/aikusrv02/_PROJECTS/wonjunoh/assignment1-basics-solution/./cs336_basics/solutions/_train_model.py
                python: CPython 3.12.4
                root: /home/aikusrv02/_PROJECTS/wonjunoh/assignment1-basics-solution
                startedAt: "2026-02-20T15:37:31.777458Z"
                writerId: 5oedx47245kbxbu76awdzeciitwcosnd
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.4
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
checkpoint_dir:
    value: ./out/ts_train/checkpoints
context_length:
    value: 256
dataset_dir:
    value: ./out/ts_train
deepscale:
    value: false
deepscale_config:
    value: null
deepspeed:
    value: false
deepspeed_config:
    value: null
ds_config_path:
    value: ./cs336_basics/configs/ds_config.json
local_rank:
    value: 0
lr:
    value: 0.0006
max_grad_norm:
    value: 1
min_lr:
    value: 3e-05
model_config_path:
    value: ./cs336_basics/configs/model_config.json
resume_from:
    value: null
save_interval:
    value: 2000
total_iters:
    value: 10000
wandb_name:
    value: run-test
wandb_project:
    value: cs336-a1-ts
warmup_iters:
    value: 1000
z:
    value: 0
